function x = ast_logpdf_left(alpha,mu,nu1,sigma,y)
%AST_LOGPDF_LEFT
%    X = AST_LOGPDF_LEFT(ALPHA,MU,NU1,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-Dec-2017 17:37:40

t3 = nu1.*(1.0./2.0);
t2 = gamma(t3);
t4 = mu-y;
t5 = t3+1.0./2.0;
x = -log(sigma)-t5.*log(1.0./alpha.^2.*1.0./sigma.^2.*t2.^2.*t4.^2.*pi.*1.0./gamma(t5).^2.*(1.0./4.0)+1.0);
