function x = ast_logpdf_left_grad_mu(alpha,mu,nu1,sigma,y)
%AST_LOGPDF_LEFT_GRAD_MU
%    X = AST_LOGPDF_LEFT_GRAD_MU(ALPHA,MU,NU1,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Dec-2017 18:22:17

t3 = nu1.*(1.0./2.0);
t2 = gamma(t3);
t4 = t3+1.0./2.0;
t5 = 1.0./alpha.^2;
t6 = 1.0./sigma.^2;
t7 = t2.^2;
t8 = gamma(t4);
t9 = 1.0./t8.^2;
t10 = mu-y;
x = (t4.*t5.*t6.*t7.*t9.*pi.*(mu.*2.0-y.*2.0).*(-1.0./4.0))./(t5.*t6.*t7.*t9.*t10.^2.*pi.*(1.0./4.0)+1.0);
