function [logp,g_mu,g_sigma] = ast_logpdf_n_grad_right(mu,sigma,y)
%AST_LOGPDF_N_GRAD_RIGHT
%    [LOGP,G_MU,G_SIGMA] = AST_LOGPDF_N_GRAD_RIGHT(MU,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Aug-2018 12:18:12

t2 = mu-y;
t3 = 1.0./sigma.^2;
t4 = pi.^2;
t5 = t2.^2;
t6 = t3.*t4.*t5;
t7 = t6+1.0;
logp = -log(sigma)-log(t7);
if nargout > 1
    t8 = 1.0./t7;
    g_mu = -t3.*t4.*t8.*(mu.*2.0-y.*2.0);
end
if nargout > 2
    g_sigma = -1.0./sigma+1.0./sigma.^3.*t4.*t5.*t8.*2.0;
end
