function x = ast_logpdf_left(mu,sigma,y)
%AST_LOGPDF_LEFT
%    X = AST_LOGPDF_LEFT(MU,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Aug-2018 11:50:08

t2 = mu-y;
x = log(1.0./sigma.^2.*t2.^2.*2.129587634366285e-1+1.0).*(-3.1e1./2.0)-log(sigma);
