function x = ast_logpdf_left_grad_mu(mu,sigma,y)
%AST_LOGPDF_LEFT_GRAD_MU
%    X = AST_LOGPDF_LEFT_GRAD_MU(MU,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Aug-2018 11:50:08

t2 = 1.0./sigma.^2;
t3 = mu-y;
x = (t2.*(mu.*2.0-y.*2.0).*(-3.300860833267742))./(t2.*t3.^2.*2.129587634366285e-1+1.0);
