function x = ast_logpdf_right_grad_mu(alpha,mu,nu2,sigma,y)
%AST_LOGPDF_RIGHT_GRAD_MU
%    X = AST_LOGPDF_RIGHT_GRAD_MU(ALPHA,MU,NU2,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Dec-2017 18:22:18

t3 = nu2.*(1.0./2.0);
t2 = gamma(t3);
t4 = t3+1.0./2.0;
t5 = 1.0./sigma.^2;
t6 = t2.^2;
t7 = gamma(t4);
t8 = 1.0./t7.^2;
t9 = mu-y;
t10 = alpha-1.0;
t11 = 1.0./t10.^2;
x = (t4.*t5.*t6.*t8.*t11.*pi.*(mu.*2.0-y.*2.0).*(-1.0./4.0))./(t5.*t6.*t8.*t9.^2.*t11.*pi.*(1.0./4.0)+1.0);
