function x = ast_logpdf_left_grad_sigma(alpha,mu,nu1,sigma,y)
%AST_LOGPDF_LEFT_GRAD_SIGMA
%    X = AST_LOGPDF_LEFT_GRAD_SIGMA(ALPHA,MU,NU1,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Dec-2017 18:22:18

t3 = nu1.*(1.0./2.0);
t2 = gamma(t3);
t4 = t3+1.0./2.0;
t5 = 1.0./alpha.^2;
t6 = t2.^2;
t7 = gamma(t4);
t8 = 1.0./t7.^2;
t9 = mu-y;
t10 = t9.^2;
x = -1.0./sigma+(1.0./sigma.^3.*t4.*t5.*t6.*t8.*t10.*pi.*(1.0./2.0))./(1.0./sigma.^2.*t5.*t6.*t8.*t10.*pi.*(1.0./4.0)+1.0);
