function x = ast_logpdf_right_grad_sigma(mu,sigma,y)
%AST_LOGPDF_RIGHT_GRAD_SIGMA
%    X = AST_LOGPDF_RIGHT_GRAD_SIGMA(MU,SIGMA,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Aug-2018 11:50:09

t2 = pi.^2;
t3 = mu-y;
t4 = t3.^2;
x = -1.0./sigma+(1.0./sigma.^3.*t2.*t4.*2.0)./(1.0./sigma.^2.*t2.*t4+1.0);
